### ISSUE TITLE
Undefined control sequence.

### ISSUE THREAD

**Issue by mablue** [bidi-tex/xepersian#5]
****************************************************
(/home/mab/texmf/tex/xelatex/xepersian/loadingorder-xepersian.def)
(/home/mab/texmf/tex/xelatex/xepersian/footnote-xepersian.def)
(/home/mab/texmf/tex/xelatex/xepersian/hyperref-xepersian.def)
(/home/mab/texmf/tex/xelatex/xepersian/article-xepersian.def)
(/home/mab/texmf/tex/xelatex/xepersian/fontspec-xepersian.def)
! Undefined control sequence.
<argument> \str_lowercase:f 
                            {\l__fontspec_extension_tl }
l.1560 \PersianAlphs
                    
?

**Comment by u-fischer** [comment]
You probably have an outdated expl3. Update your tex system. If the problem persists, please show a small complete example and the complete log-file.

**Comment by mablue** [comment]
> 
> mab@mab-X550VX:~/Desktop/PROP/end$ xelatex masoud_azizi_proposal.tex

> (/home/mab/texmf/tex/xelatex/xepersian/fontspec-xepersian.def)
> ! Undefined control sequence.
> <argument> \str_lowercase:f 
>                             {\l__fontspec_extension_tl }
> l.1560 \PersianAlphs
>                     
> ? 
> )
> ! Undefined control sequence.
> <argument> \str_lowercase:f 
>                             {\l__fontspec_extension_tl }
> l.22 \defpersianfont
>                     \titr[Scale=1]{XB Titre}
> ? 
> ! Undefined control sequence.
> <argument> \str_lowercase:f 
>                             {\l__fontspec_extension_tl }
> l.23 \defpersianfont
>                     \nastaliq[Scale=1.5]{IranNastaliq}
> ? 
> ! Undefined control sequence.
> <argument> \str_lowercase:f 
>                             {\l__fontspec_extension_tl }
> l.25 \defpersianfont
>                     \traffic[Scale=1]{XB Roya}
> ? 
> ! Undefined control sequence.
> <argument> \str_lowercase:f 
>                             {\l__fontspec_extension_tl }
> l.26 \defpersianfont
>                     \yekan[Scale=1]{XB Kayhan}
> ? 
> ! Undefined control sequence.
> <argument> \str_lowercase:f 
>                             {\l__fontspec_extension_tl }
> l.29 \theoremstyle
>                   {definition}
> ? 
> 
> Package amsthm Warning: Unknown theoremstyle `theorem' on input line 31.
> 
> (./masoud_azizi_proposal.aux)
> (/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty

> <inserted text> 
>                 \par 
> l.45 ...ne{\includegraphics[height=4cm]{logo.jpg}}
>

**Comment by mablue** [comment]
> (/home/mab/texmf/tex/latex/hyperref/hyperref.sty
> Package: hyperref 2020/01/14 v7.00d Hypertext links for LaTeX
> 
> (/home/mab/texmf/tex/generic/ltxcmds/ltxcmds.sty
> Package: ltxcmds 2019/12/15 v1.24 LaTeX kernel commands for general use (HO)
> )
> (/home/mab/texmf/tex/generic/iftex/iftex.sty
> Package: iftex 2019/11/07 v1.0c TeX engine tests
> )
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty
> Package: pdftexcmds 2018/09/10 v0.29 Utility functions of pdfTeX for LuaTeX (HO
> )
> 
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty
> Package: infwarerr 2016/05/16 v1.4 Providing info/warning/error messages (HO)
> )
> (/home/mab/texmf/tex/generic/iftex/ifluatex.sty
> Package: ifluatex 2019/10/25 v1.5 ifluatex legacy package. Use iftex instead.
> )
> (/home/mab/texmf/tex/generic/iftex/ifpdf.sty
> Package: ifpdf 2019/10/25 v3.4 ifpdf legacy package. Use iftex instead.

**Comment by mablue** [comment]
[latex.txt](https://github.com/bidi-tex/xepersian/files/4165491/latex.txt)

**Comment by davidcarlisle** [comment]
You have inconsistent installation, your log shows:

```
(/home/mab/texmf/tex/latex/fontspec/fontspec.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty
```

so you have a new fontspec (and latex/base) coming from /home/mlab but an older expl3 coming from /usr/share/texlive


David

**Comment by mablue** [comment]
https://transfer.sh/GuFqg/fonts.zip

**Comment by mablue** [comment]
> You have inconsistent installation, your log shows:
> 
> ```
> (/home/mab/texmf/tex/latex/fontspec/fontspec.sty
> (/usr/share/texlive/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
> (/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty
> ```
> 
> so you have a new fontspec (and latex/base) coming from /home/mlab but an older expl3 coming from /usr/share/texlive
> 
> David

now how can i solve that? `rm -r /home/mab/texmf `
?

**Comment by u-fischer** [comment]
Perhaps (but better make a backup). You should also update your texsystem with tlmgr.

**Comment by davidcarlisle** [comment]
It is your choice, I don't know how you got there or if you have control over /usr/share or if that is an institutional installation.  But if you update latex base and fontspec in any texmf tree you should update expl3 in the same tree to keep them in sync, . Certainly I am not going to recommend you run a recursive remove on a directory that I don't know the contents of, it might be your life's work.

Currently you do not appear to have expl3 under /home at all so rather than remove your home texmf tree another option would be to make that more complete and up to date.

But the issue is just a local issue in your installation.

**Comment by mablue** [comment]
i do that:
`rm -r /home/mab/texmf `
and problem solved but It give me some other errors now !

**Comment by mablue** [comment]
log file:
[masoud_azizi_proposal.log](https://transfer.sh/14jrEx/masoud_azizi_proposal.log)

**Comment by u-fischer** [comment]
Sorry but your messages are quite unreadable. Please attach log-file and tex file here, not through some external transfer site. And reduce your tex file first. Remove unneeded packages, content and reference to local fonts. A five page document is not the right thing for a bug report.

**Comment by mablue** [comment]
> Sorry but your messages are quite unreadable. Please attach log-file and tex file here, not through some external transfer site. And reduce your tex file first. Remove unneeded packages, content and reference to local fonts. A five page document is not the right thing for a bug report.

ok.I compacted and attached all files in zip file in this replay.tnx for help.
[latex.zip](https://github.com/bidi-tex/xepersian/files/4165483/latex.zip)

**Comment by u-fischer** [comment]
It compiles for me on a up-to-date texlive. You can try if it works if you remove the \centerline command, but probably you will have to update your system. 

As you are not using the current versions of bidi and xepersian there is not much we can do here.

**Comment by mablue** [comment]
> It compiles for me on a up-to-date texlive. You can try if it works if you remove the \centerline command, but probably you will have to update your system.
> 
> As you are not using the current versions of bidi and xepersian there is not much we can do here.

what can i do for upgrade to latest version?
I have installed it in ubuntu with this command:
```bash
sudo apt-get update
sudo apt-get install texlive-full
sudo tlmgr update --all
```
and every thing working good just this file give error while compiling.
you compiled? not any error?I have a pdf output but I dont want to get errors!
 :cold_sweat:

**Comment by mablue** [comment]
I find the core of problem is here:
\includegraphics[height=4cm]{logo.jpg}

The xelatex cant compile this line and image not shown in the compiled pdf file.whats the problem?how i can solve that

**Comment by davidcarlisle** [comment]
sorry but this is a bug tracker not a help forum, there really isn't much more we can do, perhaps there is an issue with that jpg file (test with some other ones) `\includegraphics` should work with jpg  with xelatex/xdvipdfmx.

**Comment by FrankMittelbach** [comment]
I was just to say something like that too. In case of user/document problems please ask in help forums.

**Comment by mablue** [comment]
Problem fixed after installing from iso and than update to end version of packages...tnx
